### ISSUE TITLE
Demo URL does not work

### ISSUE THREAD

**Issue by Rajdave69** [drkostas/shooter-game-with-p5js#1]
The demo URL in readme.md 404s

**Comment by AlexErdei73** [comment]
Unfortunately, it's still not working.

**Comment by Skorpinakos** [comment]
still not online 
![404_error](https://user-images.githubusercontent.com/82767099/220051468-3b1d24fd-41da-4b53-b266-7c287e36c431.PNG)

**Comment by maddox05** [comment]
its been a year lol

**Comment by Rajdave69** [comment]
Lmaoo yes but it still doesn't work :(

**Comment by drkostas** [comment]
I finally found time to fix some bugs and security issues, you should be able to find at https://shooter-game.gkos.dev
Doesn't work on mobile devices
